[project]
name = "alloy"
description = ""
license = { text = "GPL-3.0", file = "LICENSE" }
requires-python = ">=3.12"
authors = [{ name = "OLILHR" }]
keywords = [""]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GPL-3.0 License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
]
dependencies = []
dynamic = ["readme", "version"]

[project.urls]
Changelog = "https://github.com/OLILHR/alloy/releases"
Homepage = "https://github.com/OLILHR/alloy"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"

[tool.pylint.format]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-few-public-methods",
    "fixme",
    "missing-docstring"
]

[mypy]
truethy-bool = true

[tool.mypy]
disable_error_code = ["no-untyped-def", "no-untyped-call"]
